version: 2.1

orbs:
  node: circleci/node@5.1.0

jobs:
  front_test:
    executor: node/default
    steps:
      - checkout
      # Reuse the workspace from the build job
      - attach_workspace:
          at: ~/front
    
      - run:
          name: Current WorkSpace Monitoring
          command: ls -al

  back_build:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/back

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    # Add steps to the job
    steps:
      - checkout

      # Download and cache dependencies
      # - restore_cache:
      #     keys:
      #       - v1-dependencies-{{ checksum "build.gradle" }}
      #       # fallback to using the latest cache if no exact match is found
      #       - v1-dependencies-

      # - run: gradle dependencies

      # - save_cache:
      #     paths:
      #       - ~/.gradle
      #     key: v1-dependencies-{{ checksum "build.gradle" }}

      - run:
          name: Current WorkSpace Monitoring
          command: ls -al ./

  back_test:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      # Reuse the workspace from the build job
      - attach_workspace:
          at: ~/back
      - run:
          name: Current WorkSpace Monitoring
          command: ls -al ./

      # run tests!
      - run: gradle test

workflows:
  version: 2
  build_and_test:
    jobs:
      - front_test
      - back_build
      - back_test:
          requires:
            - back_build