version: 2.1

orbs:
  node: circleci/node@5.1.0

# https://circleci.com/docs/configuration-reference
jobs:
  front_test:
    executor: node/default

    working_directory: ~/front
    steps:
      # In this case, the 'checkout' step will checkout project source code into the job’s 'working_directory'
      - checkout
    
      - run: ls -al ~/
      - run:
          name: Current WorkSpace Monitoring
          command: ls -alR ./
      
      - run: sudo npm install -g npm@latest
      - node/install-packages:
          cache-path: ~/front/node_modules
          override-ci-command: npm install

  back_build:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/back
    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    # Add steps to the job
    steps:
      # In this case, the 'checkout' step will checkout project source code into the job’s 'working_directory'
      - checkout
      # Reuse the workspace from the build job
      - attach_workspace:
          at: /tmp

      # Download and cache dependencies
      # - restore_cache:
      #     keys:
      #       - v1-dependencies-{{ checksum "build.gradle" }}
      #       # fallback to using the latest cache if no exact match is found
      #       - v1-dependencies-

      # - run: gradle dependencies

      # - save_cache:
      #     paths:
      #       - ~/.gradle
      #     key: v1-dependencies-{{ checksum "build.gradle" }}

      - run: ls -al ~/
      - run:
          name: Current WorkSpace Monitoring
          command: ls -alR ./

  back_test:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/back
    steps:
      # In this case, the 'checkout' step will checkout project source code into the job’s 'working_directory'
      - checkout

      - run: ls -al ~/
      - run:
          name: Current WorkSpace Monitoring
          command: ls -alR ./

      # run tests!
      # - run: gradle test

workflows:
  version: 2
  build_and_test:
    jobs:
      - front_test
      - node/run:
          requires:
            - front_test
          app-dir: ~/front
          yarn-run: build
      - back_test
      - back_build:
          requires:
            - back_test