version: 2.1

orbs:
  node: circleci/node@5.1.0

# https://circleci.com/docs/configuration-reference
jobs:
  front_test_build:
    executor: node/default

    working_directory: ~/frontend/front   # Root Path Workspace
    steps:
      # In this case, the 'checkout' step will checkout project source code into the job’s 'working_directory'
      - checkout:
          path: ~/frontend

      - run:
          name: Current WorkSpace Monitoring
          command: ls -al ./

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      
      # - run: sudo npm install -g npm@latest
      # - node/install-packages:
      #     cache-path: ./node_modules
      #     override-ci-command: npm install

      # https://circleci.com/docs/language-javascript/
      - node/install-packages:
          pkg-manager: yarn

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      # - run:
      #     name: Run tests
      #     command: yarn test
      - run:
          name: Build app
          command: yarn build

      # Workflow Job간 파일 공유: https://negabaro.github.io/archive/circleci_persist_to_workspace
      - persist_to_workspace:
          root: ~/frontend/front
          paths:
            - ./dist

  front_deploy:
    executor: node/default

    working_directory: ~/frontend/front   # Root Path Workspace
    steps:
      - attach_workspace:
          at: .  # Root Workspace Attach

      - run:
          name: Current WorkSpace Monitoring
          command: ls -alR ~/

  back_build:
    docker:
      - image: circleci/openjdk:8-jdk

    # working_directory: ~/back
    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    working_directory: ~/backend/back   # Root Path Workspace
    steps:
      # In this case, the 'checkout' step will checkout project source code into the job’s 'working_directory'
      - checkout:
          path: ~/backend
      # Reuse the workspace from the build job
      - attach_workspace:
          at: ~/project

      - run:
          name: Current WorkSpace Monitoring
          command: ls -al ./

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: gradle dependencies

      - save_cache:
          paths:
            - .gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

  back_test:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/backend/back   # Root Path Workspace
    steps:
      # In this case, the 'checkout' step will checkout project source code into the job’s 'working_directory'
      - checkout:
          path: ~/backend

      - run: ls -al ~/
      - run:
          name: Current WorkSpace Monitoring
          command: ls -al ./

      # run tests!
      # - run: gradle test

workflows:
  version: 2
  DevOps_LifeCycle:
    jobs:
      - front_test_build
      # - node/run:
      #     requires:
      #       - front_test_build
      #     app-dir: ~/front
      #     yarn-run: build
      - front_deploy:
          requires:
            - front_test_build
          filters:
            branches:
              only: main # only deploy when on main
      - back_test
      - back_build:
          requires:
            - back_test