version: 2.1

orbs:
  node: circleci/node@5.1.0

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/back

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    # Add steps to the job
    steps:
      - checkout

      # Download and cache dependencies
      # - restore_cache:
      #     keys:
      #       - v1-dependencies-{{ checksum "build.gradle" }}
      #       # fallback to using the latest cache if no exact match is found
      #       - v1-dependencies-

      # - run: gradle dependencies

      # - save_cache:
      #     paths:
      #       - ~/.gradle
      #     key: v1-dependencies-{{ checksum "build.gradle" }}

  test:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      # Reuse the workspace from the build job
      - attach_workspace:
          at: ~/back
      - run:
          name: Current WorkSpace Monitoring
          command: ls -al

      # run tests!
      - run: gradle test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - node/test:
          run-command: ls -al
          pkg-manager: npm 
          resource_class: large 
          test-results-for: other 
          app-dir: ~/front 
          override-ci-command: npm run test 