server:
  host:
    mariadb: 127.0.0.1
  port: 9080
  error:
    include-exception: false      # Response 에 Exception 을 표시할지
    include-message: always       # Response 에 Exception Message 를 표시할지 (never | always | on_param)
    include-stacktrace: on_param  # Response 에 Stack Trace 를 표시할지 (never | always | on_param) on_trace_params 은 deprecated
    whitelabel.enabled: true      # 에러 발생 시 Spring 기본 에러 페이지 노출 여부

spring:
  profiles:
    group:
      test: common, test
      dev-local: common, development
      prod-local: common, production
---
spring:
  config:
    activate:
      on-profile: development
  datasource:
    username: root
    password: root
    url: jdbc:mariadb://${server.host.mariadb}:3309/mo2ver_test
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: create
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    defer-datasource-initialization: true   # Hibernate 초기화 후 data.sql 실행
  sql:
    init:
      mode: always  # 서버 시작시 항상 classpath의 sql문을 실행하도록 설정
      continue-on-error: false  # 서버 시작시 sql문을 실행할 때 오류 무시하고 계속 진행
      data-locations: classpath:data.sql  # 서버 시작시 dml sql문을 실행할 위치 및 파일 지정
---
spring:
  config:
    activate:
      on-profile: production, test
  datasource:
    username: root
    password: root
    url: jdbc:mariadb://${server.host.mariadb}:3309/mo2ver
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: validate
---
spring:
  config:
    activate:
      on-profile: common
  servlet:
    multipart:
      max-file-size: 256MB
      max-request-size: 256MB
      enabled: true
  jackson:
    serialization:
      fail-on-empty-beans: false
    deserialization:
      fail-on-unknown-properties: true   # 속성이 없는 경우 오류 발생 (true) -> 무시 (false)
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
      springframework:
        data:
          mongodb:
            repository:
              query: DEBUG
        security: DEBUG
        web:
          filter: DEBUG

init-member:
  admin-login-id: admin
  admin-password: admin123
  admin-email: admin@admin.co.kr
  user-login-id: bbj
  user-password: bbj12345
  user-email: bbj@admin.co.kr

cors-setting:
  url-client: http://localhost:3000

jwt-setting:
  jwt-secret: mo2ver-master-jwttoken-startapp!@  # 최소 32개의 문자열 (256bit)
  jwt-accesstoken-validation-second: 60   # 1분 (1 * 60)
  jwt-refreshtoken-validation-second: 3600   # 1시간 (60 * 60)

images-setting:
  filepath: ../data/images