server:
  host:
    mariadb: 127.0.0.1
  port: 9080
  error:
    include-exception: false      # Response 에 Exception 을 표시할지
    include-message: always       # Response 에 Exception Message 를 표시할지 (never | always | on_param)
    include-stacktrace: on_param  # Response 에 Stack Trace 를 표시할지 (never | always | on_param) on_trace_params 은 deprecated
    whitelabel.enabled: true      # 에러 발생 시 Spring 기본 에러 페이지 노출 여부

spring:
  profiles:
    group:
      dev: common, development
      prod: common, production
---
spring:
  config:
    activate:
      on-profile: development
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: create
---
spring:
  config:
    activate:
      on-profile: production
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: validate
---
spring:
  config:
    activate:
      on-profile: common
  servlet:
    multipart:
      max-file-size: 256MB
      max-request-size: 256MB
      enabled: true
  jackson:
    serialization:
      fail-on-empty-beans: false
    deserialization:
      fail-on-unknown-properties: true   # 속성이 없는 경우 오류 발생 (true) -> 무시 (false)
  datasource:
    username: root
    password: root
    url: jdbc:mariadb://${server.host.mariadb}:3309/mo2ver
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
      springframework:
        data:
          mongodb:
            repository:
              query: DEBUG
        security: DEBUG

start-user:
  admin-username: admin
  admin-password: admin
  admin-email: admin@admin.co.kr
  user-username: bbj
  user-password: bbj
  user-email: bbj@admin.co.kr
  local-address: 127.0.0.1

jwt-setting:
  jwt-secret: mo2ver-master-jwttoken-startapp!@  # 최소 32개의 문자열 (256bit)
  jwt-accesstoken-validation-second: 60   # 1분 (1 * 60)
  jwt-refreshtoken-validation-second: 3600   # 1시간 (60 * 60)