server:
  host:
    mariadb: 127.0.0.1

spring:
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: true
  datasource:
    username: root
    password: root
    url: jdbc:mariadb://${server.host.mariadb}:3309/mo2ver
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: validate
        jdbc:
          lob:
            non_contextual_creation: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
