server:
  host:
    mariadb: 127.0.0.1

spring.batch.job.names: ${job.name:NONE}

spring:
  profiles:
    group:
      test: common, test
      dev-local: common, development
      prod-local: common, production
---
spring:
  config:
    activate:
      on-profile: development
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: create
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
---
spring:
  config:
    activate:
      on-profile: production, test
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          #auto: update
          #auto: validate
          auto: none
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
---
spring:
  config:
    activate:
      on-profile: common
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: true
  datasource:
    username: root
    password: root
    url: jdbc:mariadb://${server.host.mariadb}:3309/mo2ver
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

#logging:
#  level:
#    org:
#      springframework:
#        batch: DEBUG
#      hibernate:
#        SQL: DEBUG
#        type:
#          descriptor:
#            sql:
#              BasicBinder: TRACE

csv-setting:
  filepath: ../data/styles.csv

crypto-setting:
  origin-folder: ../data/images/goods_master
  encrypt-folder: ../data/images/goods
  decrypt-folder: ../data/images/goods_dec
  password: mo2ver_aes256cbc_pbkdf2
  salt: mo2ver_salt
