name: CI/CD
on:
  push:
    branches:
      - main  # main 브랜치 이름
#permissions:
#  contents: write
#  id-token: write
#  security-events: write
jobs:
  front_build:
    runs-on: ubuntu-latest

    steps:
      # 1. 리포지토리 체크아웃
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      # 2. Node.js 설정 (front 빌드)
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'  # 사용하려는 Node.js 버전 (dependency issue..!)

      # 2. Yarn 캐시 복원
      - name: Restore Yarn Cache
        uses: actions/cache@v3
        id: yarn-cache # 캐시 상태를 확인하기 위해 ID를 설정
        with:
          path: |
            ~/.cache/yarn
            **/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      # 3. Yarn 의존성 설치
      - name: Install dependencies
        if: steps.yarn-cache.outputs.cache-hit != 'true' # 캐시가 없을 때만 실행
        working-directory: front
        run: |
          ls -al
          yarn install
#          yarn add webpack --dev
#          yarn add dotenv-webpack --dev
#          yarn add html-webpack-plugin --dev
#          yarn add copy-webpack-plugin --dev
#          yarn add mini-css-extract-plugin --dev
          
      # 4. Frontend 빌드 (yarn)
      - name: Install dependencies and Build frontend with Yarn
        working-directory: front
        run: |
          yarn build
          ls -al
      
      # 5. 빌드 결과물 아티팩트로 업로드
      - name: Upload frontend build artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: front/dist  # frontend 빌드 파일 경로

  back_build:
    runs-on: ubuntu-latest

    steps:
      # 1. 리포지토리 체크아웃
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      # 2 Gradle 설정 (back 빌드)
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '7.6'
          dependency-graph: generate-and-submit
          
      # 3 Gradle 캐싱 (빌드 속도 향상)
      - name: Gradle Caching
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
            
      # 4. Backend 빌드 (gradle)
      - name: Build backend with Gradle
        working-directory: back
        run: |
          ls -al
          gradle build -x test -Pspring.profiles.active=prod

      # 5. 빌드 결과물 아티팩트로 업로드
      - name: Upload backend build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: back/build  # backend 빌드 파일 경로
          
  deploy:
    runs-on: ubuntu-latest
    needs: [front_build, back_build]  # front_build와 back_build가 완료된 후 실행

    steps:
      # 1. 리포지토리 체크아웃
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2. 아티팩트 다운로드
      - name: Download frontend build artifact
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      - name: Download backend build artifact
        uses: actions/download-artifact@v4
        with:
          name: build
          path: build
          
      # 3. 빌드된 파일을 압축
      - name: Compressing build artifact
        run: |
          ls -alh
          ls -al dist/
          tar -cpzf ui.tar.gz dist/*  # frontend 빌드 압축
          ls -al build/
          tar -cpzf app.tar.gz build/*  # backend 빌드 압축

      # 4. SCP를 통해 서버로 파일 전송
      - name: Deploy to Oracle Cloud
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.OCI_SERVER }}
          username: ${{ secrets.OCI_USER }}
          key: ${{ secrets.OCI_SSH_KEY }}
          port: ${{ secrets.OCI_PORT }}
          source: "*.tar.gz"
          target: "/tmp/"  # 서버의 대상 경로

      # 5. SSH를 통해 서버에서 명령 실행
      - name: Run commands Oracle Cloud
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.OCI_SERVER }}
          username: ${{ secrets.OCI_USER }}
          key: ${{ secrets.OCI_SSH_KEY }}
          port: ${{ secrets.OCI_PORT }}
          script: |
            # echo "sudo cp /etc/letsencrypt/live/api.mo2ver.p-e.kr/* /home/ubuntu/build/resources/main" >> start.sh
            # echo "sudo cp /etc/letsencrypt/live/api.mo2ver.p-e.kr/* /home/ubuntu" >> start.sh
            echo "sudo cp /etc/letsencrypt/live/mo2ver.duckdns.org/* /home/ubuntu" >> start.sh
            echo "sudo pkill -f java" >> start.sh
            echo "sudo java -jar -DPORT=${{ secrets.PORT }} -DKEY_STORE_PASSWORD=${{ secrets.KEY_STORE_PASSWORD }} -DMYSQL_USER_NAME=${{ secrets.MYSQL_USER_NAME }} -DMYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }} -DMYSQL_HOST=${{ secrets.MYSQL_HOST }} -DMYSQL_PORT=${{ secrets.MYSQL_PORT }} -DDATA_BASE_NAME=${{ secrets.DATA_BASE_NAME }} -DMAIL_USER_NAME=${{ secrets.MAIL_USER_NAME }} -DMAIL_PASSWORD=${{ secrets.MAIL_PASSWORD }} ./build/libs/master-0.0.1-SNAPSHOT.jar --spring.config.location=classpath:./,file:./build/resources/main/application-prod.yml -Dspring.profiles.active=prod -Dfile.encoding=UTF-8" >> start.sh
            ls /home/ubuntu
            rm -fr /home/ubuntu/build
            mkdir -p /home/ubuntu/build
            tar -xzf /tmp/app.tar.gz -C /home/ubuntu/build --strip-components 1
            rm ./build/resources/main/data.sql
            ls -al ./build/resources/main
            chmod +x start.sh
            ./exec.sh